import './globals.scss'
import { ReactNode } from 'react'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['cyrillic'] })

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
}

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang={'ru'}>
            <body className={inter.className}>{children}</body>
        </html>
    )
}
